{
        "count": 1,
        "reason": "unable_to_process_some_files",
        "diagnostics": "Some files could not be backed up. Partial list follows.",
        "list": [
            {
                "index": 0,
                "path": "C:\\Users\\admin\\AppData\\Local\\Temp\\3\\AdobeARM.log",
                "type": "file_or_folder_missing",
                "description": "The item was found during the search but was missing when we tried to back it up.",
                "exception": {
                    "code": 3015,
                    "description": "GetLastError(The system cannot find the path specified. ) Cannot open file \"C:\\Users\\admin\\AppData\\Local\\Temp\\3\\AdobeARM.log\"",
                    "details": "1: [phx::WindowsFs::Open: 166-phx::WindowsFs::Open] Ex Code(3015): GetLastError(The system cannot find the path specified. ) Cannot open file \"C:\\Users\\admin\\AppData\\Local\\Temp\\3\\AdobeARM.log\""
                }
            }
        ],
        "links": [
            {
                "href": "https://cloudbackupapi.apiary-mock.com/v2/backups/0d95d699-d16b-11e4-93bd-c8e0eb190e3d/errors",
                "rel": "self"
            }
        ]
    }